apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-secrets
  namespace: web-site
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgBB6Jz1QTES9cVYz/j4WDlB+jbIv2FxKp4WzIQLrYK7zOfDkYbwMn1B21HM/1qWpS4FoXR5QOf1KPondA+p5I6SU/tXmeXSzaxKuqbA57K9f3N/X4RqDcLUwvn5gcyYgtk13tUDaDEfQpIL/MLK3gVqhTTKKQhtnhy3e/czwgmekc3sMXv5AUoaCSAxxqvRSZi/dte7lVd8AmEdyfSiJPLAWiBuZsBGdzSQTkQfCJXtsMJMQR/WZSIJAxrFN/MSt2ywDF9zb1FTKzPdF/FvBHXIruZ3d8yTwXv13ot/7GBUS2AghWuVtw7LR/9sGPnb5x++UAOe/bnimUWwdLSbTRvSCAf5gf0KWbaYX0E5HKZSkSf/kWEV9fbgjGbfyfy0JfTgd6g6gGbo2XkJOZAxGmfPy5xbfDg1GwkHUAhW6jL2118CBM87aJeuwGeJJPaqZdt3n8Yf4Rch+bm7lg+gbkr1CuaVUp8en2RvuW1X7FZd884mTkHFcRGzbKXH09/Kp6J/V03HSD8ut8RSDnccbKVDxhd6tMFSgJryzB3zNSR4wpboJLS3gPFjY90tbxLoULnpVw3Ft+RZpZ0S/omoMl/hMwumE/dTvqRQUUNDpiY6AlLe4qlBHYQaeigmHyglxRYuElBHLPAJHsXjidNiXncQiCoMOSLys1W93cG6naC9SDY9uOYIDW0vTJOmZBiACfl+yNgL8J7gJF/vhsyRNjk=
    MINIO_ROOT_USER: AgAFF6nQu5NZQvF7UPrFKke7eZi4YU0v8nozfqGRJxfHlzyn2hXffRVMMOLxkCm1DmnhbMrVmTG6GhVXZ8njcmBHrXbRWNNunMZeOO2dFHPC6nLYq8UpVOPdXV/PmzXz3oQhFPdmqDy/9uchUD0qbPKC2pXVF3QNqfPBGhkRG2Dl9LpVFdaipjBLmkokSorLZGijF7bVy6TIFCFG003XsWPJqGajpZEfQGwchIBeegh6uTA8fYZoD3+IGXVP7wTkgq6xoC2eXGD9Fux65yTklfdcN4BsLf9FN2ZacBUZfHXbzO/6N3UOGtFLqjcN7iZL2T7iqu/DTmNXf4BTmFOdhOxzyv8nZ3bQqgsRBEio5nBBdu4v2jIVL0gaekVT2Fz9SwO7s0jGP8mCf4ws817+l9TJoJseHd+WH7BgBbzFmX5c6T26sTLQHmMMJ2+Gl2j5OlH0SpghGBpUqTLWA7ltOS3xTxStekVBYgreNLTJ7FuEU5XCKcGj2Wde5VH+utg7dD0XIoEzF7K2jN5el+r2C/0BHgnS5C58dQ1I0pE8SwQCOkNVbQxNUYeSCWHrGgMts5URQ61FlBya/sPr9ACqhnma72cKpW4HdRDY5AoiByvkJP32JVVvt3fxM8shaihvEL8vxeINtX4ZVCgw8Ej3fjXJ6yRSb5vw4pNzevnAORafjauU32Ozu0C6ShRt2iWeBD1NjbgkzA==
  template:
    metadata:
      creationTimestamp: null
      name: minio-secrets
      namespace: web-site

