apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-secrets
  namespace: default
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgCV5YtbKQ/rBzydv2OCQPckfpsQ1RZdUUDETpTNi5IFeALYbFs44pLajq+BeBdH+v+JP00ZY03m+2z4epA8ZaiKSSfGSfY3pq7to/9uS1zP5QD1ILp/F4bH6/YCYpmZBcfN+H7RpEiPjfGRPABLcqUVE0/P1Ee8xl0lDyY6YCj5CIxYIAcoGjj16/r28uh5y2p0LDqK0c0HYU5HMW6c5Y/EriYLd0AtQ88GVjoNMFxphpq3ZX80WbDQtg5cgV+DtMqhgZ/FlgGgdc6bJl0uloBXgQKLrLKfVUyC8NK3Q41JVo5PxOz/K+W3H9FgnZfSYIsLN2SUQxBiEr4qwDDk+Do/Md9NuOryseFe5tVu26ZfuROujBkgJhxkm0hllXOr9z6dn63Axhh49hsTzEIxGE+x6gAtq/KDIt4cBaWG0ky1LsddzNgqOfqVTEwuZkuCLZO2y2UQa+O21n+uicbofwCPwClgsZVpVkWz63308d+UvGTAFUHJojSlWDGe4Wp7xbKgj9eSHNHUXQTzjFErHC7szs/b8vr2cpdmLqX6Lwq3fJLB4IEQwyrZs+A/pHI4LLE3H3Yf17WohD2NPtj4NTH6bAgaGeloiuVLj+TdT9axrYoF3708fzQu7I19sGcaETMXTOzYoH5OAAFTXURSno0rWbZIcDeBtBxlRT654nPYXhCdEeJoSc/Eem2cL8TMHRYgNolQq14jYNeEOjI+fts=
    MINIO_ROOT_USER: AgA5rWxOzpOiUIv2hoPMOrtunY0W4fisav9psn9BvIS/nR19kdXj31x4loP/A/HIF84O0A/TU35q2ofhOXMBzAJidi8WF9M03yaaFJBUpITUBnZkV003hRomEntEAywg8FSX3aul6NfNEi9Um3yaZd8wetixgYtgD4LAD0hLcTIXG9UlTD5+Ab7JvF9ET4lWCepB8XrS9qvjO7iKouvifZ6snB+lgN/R2mpVNsmyz6Ix6B/4+BU5egvMWgLmunXmOuuavPdqYzYJlOGafDAtNGc1LwsnKchAyOMPod1gsOesb87Chhgp0uiMIpFHVKRoQuKxQtzBlPpbPVxAwwo8shV23RYt+TBgMm2sTemtTFYLv83irQePC0QDn43U8IaOzp1S3nTOPzIVTr+UBYUVX2le31JkE9S7r1EfPl2yp5u2LrgSuT23AFeoHma13GiK6JNgfJDkILrP4RhGnlA5npSgldtVs2MyrLV/xzZitql48mTQJKFIDouM1o4Zkyl1rKZ9D8eTnMfwmATEXs7tl3IeXHjaezPqq15p5+wfbabbIM5+YCN40EhECXDqNogoRjIn9x55R1FbxfwyOFRipxoblCw/2WZZe5ZZFpjpFFimiA73e3UNoVjr6hrRCV+Y6wbRHwyX6C6mXaRT0AvlmbvRKss2lBi2yunUcyNjQOS2Idx/+zZHR3VVDE1t+UnTgbLmPATK0w==
  template:
    metadata:
      creationTimestamp: null
      name: minio-secrets
      namespace: default

