apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-secrets
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBFjeu2ZTvt2L/7+CbxPnyEFwHVvfwOWStN1wmThfdsZctiGBKNeG2Q1d14ConBNUdzXPVPlfbxbGnN30DfXdI23CVwM7Gx5XHssRIhgISUYUv9cViua6JHgJZ8+exc1km1xrTbngoT8x+g/A0cA0D6mPCXyomkTnhzfOGbbMX9+AjbnhFBsX96P2g7WRTJNTfipcIqqcx4X8xC+n05Nv4rU5HFegqjmEyGkdwQSaTT32xdnGKJsaARQ/AoifU1Ssxkd15/j1ngfLaGqWE53JkZTauwUmyTuMmOEnqW0PzDTpupRwSh1jVEq3UkVfzXzHaJUKmXLgxRCWiaRVVXxm9xUzYFt0QFXOclj7X3th/plsg6SiYNpRhJ27/y20tjxS2Zk14+zUlP5DAf5HfPAlAlC050W2RoRn0XQPhr0Znmg71ZOQZyVUGmuctEOItowxP3qumF2uIEaGL1rF5uaLBxTULpycHgK3/ofPMjOXf23yOFqtriH9LSoFVNo0ymLdAa9GQsm5P8kWzDC9CoEp44IUN4HbYjk8z7shtFl6JMMuU+cLAX4BpgyvESTpSIq82WPXqWbsnwGPau5xLpJoRVovw1CP9PfMU2UpZSX0D/07siyzPwcQwVvG3km6eiCWGerSgqneExU5EG8QO77zRptkNVuSzEe7wXA8X9sE6Osx5jB/+SggI7YKXuB//klHR/MHBD+ZwP+yDqNeM0CDFS6JnKUQ==
    admin-user: AgCHzu5WxmR2Ss+uD2djUBFG0LehMhKwaXNMpJ3O992sBuHopoQ0bup76iHjlLa37IGOCClWrL8TBV9LOHgnL3klYxdwcRyP3GXKYSJohUY2sBOugAlvvqObefhJliyM4V2yiARhdZ1aBDAb/El0EmIqrnTS3I6jksnL/QrxcKnOV47W+w1t5BATkgyvuqYtfsjECGrODlb7kcrOB6pPTESvrb0VTuQpg9KFyoFHDKlMHBA2fevrCe7OzUrDhoz6um1mWJ6gTKdkeCwXVHHORWxq4EbQO9nFr5r331XdS2gNRtRsGKCtpA6Z0wXR9WDSwPUXZvv4mS6ctEjC9JYh6Hm0SzOMPdz+Wrq+BdSiaKkn2wkrPAbUTYLptsFLhDAbEiDSVRP0Czy3N+vr2A/CU2/FichAePBh8inhdotqI4cnz5mI9Y/bIcyu4t5jW55XpzQUbsVY25IqMITBgOA1+I6YItJkG74E60sfDXxgEUV/V8FhTOtTxhjOSqotdEFkUqJSlTT552xAUOyAu8X/lx5nt2OOmbOvQ7GSU+69HAInvSXvwkp/sBflKg4uGsFlss7I2XEwvAvPvCf340WZIH9IIDOYKUtBvSUmGwFQWcXqILSCjFERrSm+GzyM38jfQ1fAnAbA+cX+RcFMmRdbxwRZwYXjLb9JcweVswFQu9oAwH08MTrfixHhSfDBWfzOBACqPJaUkIo2eac4ZnVhywhOinYt9Q==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-secrets
      namespace: monitoring

