apiVersion: apps/v1
kind: Deployment
metadata:
  name: affiche-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: affiche-api
  template:
    metadata:
      labels:
        app: affiche-api
    spec:
      containers:
        - name: api
          image: ghcr.io/week-book/affiche-api
          envFrom:
            - secretRef:
                name: affiche-api-secrets
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
          imagePullPolicy: IfNotPresent
