apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: garage-secrets
  namespace: week-infra
spec:
  encryptedData:
    ADMIN_TOKEN: AgAwlHseACjTI/0LAZ3q/7veWLO2G8V9Sof6Gk6Hq14qEQmHC0/tPIk4rbRHzPzx+uw/a5JIhWsiWuH73/GuMVELD07O/QFWZEqXnikhyOfcN4wrgch6IvHW027RYRTaYs4f3r0oHW+2RqzIIyGGOpDniTk9nawGiTpAWuYw2F2DEEeUPJCwskccpB1LZIcezOBUPKAUKc2yL2Z4hR6wsC/a1CRzFKQt6Pl/uFu08SXnfBsg+uF1XukkrtOjTfTTW5H65N8GiwfoxA8KVCFdDhSaY/1ibW6E5KRIzX0rKSDDnRBNLqhnHI4Z16sITvUYRe6w8WUp2C07fulHQvZpoo4TkjT/EY68yDRuoCaB/2cKkwjxECCMJcT1m1bLL+omwwd99ryN16ScaG0HhAvCdtEboWKhJnoW237yCD2Xb6IBFwJ7WkDMKY3ynoutIXUm0tttVxoasJybu0V04lvAfRMTAG6vHmGXJHfVOJcuN7WNNA2J7dmjczNo0OETD1Pl4ijWYYmHBFjOqbcnNrSor3Zw3S/saf0A3K0Go87R6WW7Ta3vGpTXzRapPqxRsJcZr8IhKj87riRx7cR9/OBR2TGks73AXF+k5U2FWEYboTgwemDgXB9cinhHUHyB2WZ4m8If4VT1rH5oo/DY4KdRSKoJBdYvBNHyiMlbIairVEUcCa6WL5HsrmUNLKdMHeOOYrPO9XX9R3SaqFXoF6CBTzxaX8Uu7iLG68GMJU6QllJUA4IHFjhBJbm3aEHhNA==
    RPC_SECRET: AgCtsK2J/xidvWh/NNswFZfWpdwRTFnLuYFb5VxoM10YRuoAvadP9jTASOdZIZDj4UO7aqEJHfmuC73qst4FSq3BhfzR62Ygx+jucp4cP5+/eVZ/sv1GjhPlm2IgxI1I0dkjl2T6iKFgl6VeI9Y7cuslyHmSzgNqsk7edQa/7uGJJ5RueUAIjlJZlkyle7xwgtjRK6lEe9UpI42cIGujDQzScdlNCO4tz6bqsesgKVQn1n5KgKNqmssQNO4YAT0DatCMD2PcbYnpdyZB48n7uAdUMRLcSLjjNjXQsuwppKZe4lhz1GLYGNulryBBznBUFbdf8DtPVk0Z7p9dgtFNQzT4cM0smBpmX4lAJXRJDOUnr3QM4cQGBae6wG9VRVRD7L+kUSa5kqLxFiPu/c/vnJJbKRzxbaDjKa9chDyb3giaZqUov0O62qMvX7bBk4ShXq/q+wzTKgrl+OZIckeel5XE4I7f0pdYB1kmC/HeX07ekjjI3dNEUj/PQebJMK4tUnDhqMH88rD0YuKSjBgG1k5Nnk1XL7dGLqFTnQ77c/JB0QivHA+6qmCxtih4Au6+bbp3pKDR6KOwZYwPvcQbhQ/5bsKHz2hXLtTyRRDG+zBFqlZc/BAM/hg2fTKuVi9OAaejUBKm6XU+02fYNY/pgUfNfD5pJxA5YkTLSGSE89fojvzV4DbflmqtBdxHU+QqTuPQ8ha64j6LT+4uswnWmeDr97kfF3woSBZ9PawEIyNzArl5k+Gm1GP+trP2M/IsdD2feyTRLoTo83IAfmxiXWIM
  template:
    metadata:
      creationTimestamp: null
      name: garage-secrets
      namespace: week-infra

