apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: week-art
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/week-book/k8s-manifests.git
    targetRevision: main
    path: week-art
  destination:
    server: https://kubernetes.default.svc
    namespace: week-art
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
