apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: week-infra
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/week-book/k8s-manifests.git
    targetRevision: main
    path: week-infra
  destination:
    server: https://kubernetes.default.svc
    namespace: week-infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
