apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - secrets/affiche-bot-sealed.yaml
images:
  - name: ghcr.io/week-book/affiche-telegram-bot
    newTag: sha-3989d82fa744dd028a7843e542489ab83c029432
