apiVersion: apps/v1
kind: Deployment
metadata:
  name: redirect-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redirect-service
  template:
    metadata:
      labels:
        app: redirect-service
    spec:
      containers:
        - name: redirect-service
          image: ghcr.io/week-book/redirect-service
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: JSON_URL
              value: "https://s3.week-book.ru/posts/index.json"
            - name: TARGET_BASE
              value: "https://week-book.ru/posts"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 10
          imagePullPolicy: IfNotPresent
