apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: ghcr.io/week-book/redirect-service
    newTag: sha-4f7499b9a130af5fb1a9ad26c7297bfad1ddc748
