apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - secrets/redirect-sealed.yaml
  - ingress.yaml
images:
  - name: ghcr.io/week-book/redirect-service
    newTag: sha-39dbeac87848f1b2595c33bba293e94bfcf931aa
