apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: ghcr.io/week-book/redirect-service
    newTag: sha-b45095ae3118f26c95ab79ae17a8160adc8a3ae8
