apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-secrets
  namespace: week-infra
spec:
  encryptedData:
    REDIS_PASSWORD: AgDA9MnADALz3oZQNzNQpfenbKHGkA+lLPKb3R8tSc9OpmqSPGOTEdL9uGu9oJScJevY9hV2/RvxjwYdiNlKGCHkdJfqnqZp6mshrdP+F5SGElb4Jjyx5Esx5MVtXKRfYSAkRRwj4HgMO2G82vNcQsTVe1DP5U/Y48rta4ESFLZHyM7p9RSyz6ZIYpjudyFmCNUTwBFePD4JXGelDsUoaSbq+R8nFrSbo0gkpLkhmmzC2V2eEVEH/x5umpGaaBoo4qid2hbdCTARzkIF86Aw9iWHwZPDPtXjh7hQrRhG6qtI+FEM0AtReqL6ghOSuqIZ/VkbqTli4tb6qIiaeoZWhpkD7NIJQxwDbKJTJ8+bsym6Or2YEEv9WRzzXGYNtz4YYrD6/yOH6YTfyJe5Uav6JNiPRMS13E1otRefJwaKeDD4QCYMl7JLRqrZqPGZpHpqa7qgt6OzVAgYfL839pvb7ec5HXJug+p1+bDN/iCYDqil70h976tcvy8VDejlEqZvz0x1RkwU1Z7oIzw7rGIishNrKrUAT/vn7bSFcG7LXLivDPy5DSekkd/trGK4mxhwiT0DHz41RGKvPp50ik6QOnjXLVj/1Tx6g+EPjP0dnGDynBUSjR3mR+i4rFeCXyKMDpPILNOtV9gmpy6RFZjaLDqstys7URz7Gtkjvrxzw2s6PpuAT9HMFgxnwOuW7vQFnjvwWzHZQoNxtn4i62S8TVVqbcA=
  template:
    metadata:
      creationTimestamp: null
      name: redis-secrets
      namespace: week-infra

