apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafana
  - ingress-nginx-metrics.yaml
  - ingress-nginx-servicemonitor.yaml

patches:
  - path: ingress-nginx-patch.yaml
    target:
      kind: Deployment
      name: ingress-nginx-controller
      namespace: ingress-nginx
