apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: art-api-secrets
  namespace: week-art
spec:
  encryptedData:
    DATABASE_URL: AgArQD7F7P0y50bXZ9ZsSWCggCNCsvgnz7nL8dUdLHPRDhmK+67ZpzHYKNmwLClbjh7PleqW5Yh1aZQNt1vMPmpMA7S+d1mBspK5wIDrTT8f/4MVRXR0rNFWpaqUZaxY5KEDly6UDnRpO2qOp01oj7wDqSl6wg3YGbWzMYRaDn2OtwBem0mImAWeynQz9bfmjAifA18Xe2AU7Xgms2wzrA0XKXM9URNEOW1i7fQK3E4o5HOWkBYmxK+Ko6a29H3gFztMszoi+rnxTh4qIqCnTrZIwIX0OZxdHl+Dnof80UyrljCDiOu8eyghOfNrL4XU7eeR6LoOQCFQppa7dPvNxPBQYKieRPkJ+ZRNbZl/na1zWtl3F6CIe0AhB0aVzbK0zwG9vA7I392SSGb2c6QYwDF4lddU4R5QfZmVvII4xufVVbMftUAMhyFBQwl071FlGLGl0q/iaXbiS/APoNwNVmHnR4A4RQdQHLJuMqfelzp81fB6l0P345rdRAollMoa4SjF8jJtO3e2tsIf7GisF+tFt6rZBFcl8i+L1zowKg+6VCOs4A9Mdc0EjL4mXzclI7bRaiVfwfxboXrl6erj3UHYr/9xeujOBkuKFFY0shwWn/zLfraHOTW+hi7sREIJcKZNSUji8LKLH09YVnOf4dyEihCY+Ef5SUDWbTQW/Kf/t48E4CkgchY8tlCGxuf2jO+DHvH+PCSAn7vOM6UgQmpaQT+Nx2gn6Xu3W8bVdvYMhq2ktdf091hS4pFoVrSS95/uYhBaHr7vpdp5fZlmNkPJmJGb1x37CS9xv3cqLyvWqLE9sXEQWInfCy6BVtIVJTTV5lkckStmcmoVHui+OzM=
  template:
    metadata:
      creationTimestamp: null
      name: art-api-secrets
      namespace: week-art

