apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: garage-backup
  namespace: week-infra
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
