apiVersion: apps/v1
kind: Deployment
metadata:
  name: affiche-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: affiche-redis
  template:
    metadata:
      labels:
        app: affiche-redis
    spec:
      containers:
        - name: redis
          image: redis:8-alpine
          ports:
            - containerPort: 6379
          imagePullPolicy: IfNotPresent
