apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: week-infra
  labels:
    app: postgresql
spec:
  clusterIP: None
  selector:
    app: postgresql
  ports:
    - port: 5432
      targetPort: 5432
      name: postgresql
