apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: ghcr.io/week-book/meditation-timer
    newTag: sha-1150530e8bf085a523eeb8622164dfbdff8559f4
