apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: ghcr.io/week-book/meditation-timer
    newTag: sha-3de031f035a76992129d01021030a6636d557774
