apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: ghcr.io/week-book/meditation-timer
    newTag: sha-8cdeb6ce2889f68d121078ac5109fff1dfe9ff00
