apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - statefulset.yaml
  - service.yaml
  - ingress.yaml
  - backup-pvc.yaml
  - backup-cronjob.yaml
  - secrets/minio-sealed.yaml
