apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
spec:
  serviceName: minio
  replicas: 1

  selector:
    matchLabels:
      app: minio

  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:latest
          imagePullPolicy: IfNotPresent

          args:
            - server
            - /data
            - --console-address
            - ":9001"

          ports:
            - name: s3
              containerPort: 9000
            - name: console
              containerPort: 9001

          env:
            - name: MINIO_SERVER_URL
              value: "https://s3.week-book.ru"
            - name: MINIO_BROWSER_REDIRECT_URL
              value: "http://minio.local:9001"

          envFrom:
            - secretRef:
                name: minio-secrets

          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              cpu: 300m
              memory: 512Mi

          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: 9000
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 5

          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5

          volumeMounts:
            - name: data
              mountPath: /data

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
