apiVersion: apps/v1
kind: Deployment
metadata:
  name: affiche-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: affiche-bot
  template:
    metadata:
      labels:
        app: affiche-bot
      annotations:
        rolloutTimestamp: "2026-01-09T12:34:56"
    spec:
      containers:
        - name: bot
          image: ghcr.io/week-book/affiche-telegram-bot
          envFrom:
            - secretRef:
                name: week-book-secrets
          imagePullPolicy: IfNotPresent
