apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: ghcr.io/week-book/sudoku-frontend
    newTag: sha-87f7ef8870d816ab70735704ee99201ca6d3db08
