apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - affiche-api
  - affiche-redis
  - affiche-migrate
  - affiche-bd
images:
  - name: ghcr.io/week-book/affiche-api
    newTag: sha-147596a239fec2b237f93d419ee48e2d8303cc66
