apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: posts-api-secrets
  namespace: web-site
spec:
  encryptedData:
    DATABASE_URL: AgAWyRzjtWZ+u12/fKNS1myWjhT/gwqx10Sk/Pm2aLU4wxCEXYdTmD2hisySGY6BFbzYUX7Wl2yfgE9RlIdVH32yG63KZG2msHFF7kiyRaLHf5cXdsAkEMDHF1GN0iEGOaPAgpmuhZTqZn/jv412nMoJUM123qz/Zfg6Glh9zT7wvs88Y/vKyLeJFPyip1HHeWTTk60Am9IUE+/eAStTJ8FhlHNunqzOhhE6ngcLaMrF3ZE9WrQfElHuW+SUzOPOBKne6ZbbpCpehTJM9rQKNXmmh8HO8H2myPS3gL34CwELFIuwzm90Gmnlyn+OTbK5ZCGY218JW149u9Bakxo+6rDgnVgAQH3YMQXuxlLkAFm6LvpDmu3CWchGZwJXjsD2w2LchlF68sxvDZHotJYhgfJPcr0BEG8OpkyEyFterO64R4Lz7iY8gYxWTFy/PzIGyeC5XyMcuqHuFoXACVOgh3Ar03RDjbhsOteV6HaXZS/IlH+RIiBTH898GH8vRf1zT+M6xLWWrcfxB4siUlizDaGv6epsz3duiVaVFsei4bUNcWHt8XIYgWKQW2GR314R89yhq/1ey+IcrwieJGtw2x0GSbAd1h3NlQIC5gGO319N5B0w8xGKHrXBxnzthYuRoOOu9swKMmZoXXwUQiVscbdzMuzYiEATMTE573iapNm+2dF+X0oyPgQDGLRP4dUdLuQlFlDSs8+35HUykxLb0xKw7CFx7V1vZds/0QSi73OY5yqpEP28MQYYFarXQ1ibsfyAmmiZRoBhwQQWBziI8NkvAEH8HN3H9vwgzqm7gnm7A4jCh4fO7vV5yXPM3Zx0btdtq0Ou
  template:
    metadata:
      creationTimestamp: null
      name: posts-api-secrets
      namespace: web-site

