apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yml
images:
  - name: ghcr.io/week-book/web-site-frontend
    newTag: sha-508164f4a4d49b067d63f6478d837c12645a059b
