apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yml
images:
  - name: ghcr.io/week-book/web-site-frontend
    newTag: sha-8375b75d6f3f2be2b72e8beb01724860aecc1fbd
