apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yml
images:
  - name: ghcr.io/week-book/web-site-frontend
    newTag: sha-9f9290d761e10dc6746b0c923cc9042e4721f020
