apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: artic-bot-secrets
  namespace: default
spec:
  encryptedData:
    TELEGRAM_BOT_TOKEN: AgAJJTdCrSStmCXLKEudczb3b3zyS4rkyNcqY9c6koA4w5VHJ8m2juFC/UQPA5/4cEcHXEX5jEoU8s/hHH2wEU1c+R4vOVa+A3flbDx3/Bw/uYk8zcSzmfZsJ4qv0BVkTcnmR8EabFnjV6ghwCIyj9yGw44QDF8MT4ixiFYeTG6Sq24whAQnbMLFKicpgNRTb7HoDE9RQurjwmObrzCmFVWGgzV3osQdbSuHfAa51USyGDSbA25q5QyH3ksJbyznNez+lKVwvmfZipjDE6OGkkxp3YlXIBSYNIBTxvjv9RDuLCq9QoNx4Nr83yeV+dsG2UFyZiZa+XJ4DdqlFJZWqW7XGpugqX6/Lk1H95HzITjkh4gxpUpwxQEhxT7yx9qtIqEArzen//xclhl3hXmGfQ+oQjkjCh6i0LPdnnqIUX1SdJobI7cRtbdQRl2xRJdbS8VPXuUbEPJGyCfQhVfOQpp7VHCr3dNU5N3KNpN42WPqD1i2/Yr4eAFyIDvX3jst4e+t69QGpvt21IQeF6A/T3Suz79aeDetwTNfHFFw9CxBeAjJMcQi6Wn4asObM5tANLncThRXDUe0CqIy5OkfpneBkm+WgpBaRTGryB+dsu4AikavKBMUbYjVGvleMel1BtKCwGzaac+HvPsEy0sus8U2ggWI5YeQ6KkFDQRRmrwcTX0mKnhtK3Ei1FLtlx3Ga6KeJ8h4TF7tpIloHub9QzCDp0QSkL9TxDdF88uJo24ZKG77U/OJXim4T9mdfll2
  template:
    metadata:
      creationTimestamp: null
      name: artic-bot-secrets
      namespace: default

