apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: artic-bot-secrets
  namespace: default
spec:
  encryptedData:
    API_ACCESS_KEY: AgC5fNFzZHYwIsZGr1pe3qXv9SUZjGY6xFnhj0zbf9i3wyS9qqiF/tt55wf5X44bctdVtpH1RCmK92d19FXzBE9NA0YNLT7YLZVaZn8BLoviS12Tdqc5klVNmcFoUx7Z61H1KrHBLHCvkrjtY261Ue3va/RDVkLtLiQziidlzX1eilML+lUAkpEETGgrAWJXR1Gi4lmI97Y/bgEttoV1AjwikU6WXUZtbHD8hSskC6/C0FCpHs5rN/5eqBoKzMkK6BAsn96ImOriwjfrwsFFFQi+Hj4aCZc2EYYvt9plYQzf07Kmt1vhsv8XH4oqIMqyx3cz2iWdJ68eJ39f/2CQNm7/ETGPyoxaUEfscvJT/JxlZDd9pLVts9OE7zvp6Sjw8IstDg7Nq3Vpg0TSpRx8qloFLbVaLIZ7kGjsUhWFSLGJTyYUW5KXTFS7NFmehmy88ifGaWpoZasTyXazJF/6GlcbFtPoPYf4TzngXtWqeNU1oTT4aSLzbmJP+3egfClrKz+xzGNBGol7w5bogO18oEPfjnwNrfcXk2cU49O0FHQyOcM497aBUmE25tKWQkECcBVYZ1jEu5HurE5eN+IGNZyzRbnLbor7XdF3i3gUoi9vaa1W32gOdQyafQ2u6wp7MpMjB33ZbuSkYktNCl0CwIqMFZTjN14R5I1prETGx5Gr0lf9UaIZ7VLqtMdRfnqw82jakGPCpBK5A/5Xa56cYZPKrJhfbBbNJzdsp+yxBKbzQ5GN9PDDBSNIxqw/
    TELEGRAM_BOT_TOKEN: AgBAbN6bLVd6cUN3zcDt5sXxaevtAJ0jHFhPStwzL3X9kZfPPaFCX34KyWYZjVTXjvIO81zdyTwAoaJ8V35Vn8WpdVI+IYWZ7h+BzMHd7QP4MSwOOiZOP+A6bWubKvX9iFbigLQSskWpuAXgIjWwN6AI9jcsMLl6uCRwA1LWnr5X8fCAFCBXbBjHtgbyS1ItgoAG68xTHOjp4LK+8pIj2GxkHftNMEASDYRDUFCemuYYM/xixqBvxjZHx1IDyfGGhADV137Y8MDd/yGksrObpFdskvVO6PFUlyVA4nZPVBKhHP1x3BnzgT/L2aXUn9zrvGTCirG8Fh5iHk++I5oDs32v4a3fbV10CozGbs43y7sUSNkZNzrK3gtkcx4wZxgM1rL/VmSWK99utiL9BYJRTRg39Fd2yzMJNE0oHcLw2NE1EdIUVz6ZbeEHh2E4SMcc0Sk6l6UR7QuXJA7+P+ZBlXWZcBsHjFqLcmCZSWw7tB9+mZsJl5NCzGVKQlSOKt14Ddha8L3598IWAa59RKYlirxF7HXYzm9NUeCP1BH4ApKjVSYzrmwMMkmWq5yYl6eal8nAylMZ4auT4F+fpHznBBTWW8IxZEvmfCeZ6479bKUQwXeU+YNyVIFLUJPg+PppcneLnkZt0qVlu48bGgprvuWz53TSs8NwTiV3ZF6p1lZ9uzOe9qMenLKOOAjiHv7RpaK1qJ1YlI4umUIUwI22kBZ4GiFenV5fAmZAg2ZE/hvPUOJSGFMe/eP3w8iz95Vi
  template:
    metadata:
      creationTimestamp: null
      name: artic-bot-secrets
      namespace: default

