apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: artic-bot-secrets
  namespace: default
spec:
  encryptedData:
    API_ACCESS_KEY: AgA+p13xLdlMx9oquNIGKDaaMoTVI2V8eJONQCuBBUKiPCcs1wUGJUyJhA6MxfLkuYa446wx4NGl3+n2E6HcNF9wY4n84d3h5YL4+jDqLoqVR3Us0WViBqk9n6bc7Gpq2Lglr0aPE+GftU4Zn5ODm1f/B7u7tkjxWWHiFof8vHC/5XaZzgF/xwRy2CcKa1UMVygYgy+u8iCd4FWw+YTequ2zFkTLwZahJCahH0bmhQuWlOcOA/D5KGS/hRUEdQ47Z0SNtE6pdUlefj77hDeQFAqOb85jbf0IcBUD+16M6SmReZxtw9uaRMb2+WIY7qY23rIE4rukJN7To+5VsMtHN0d3jxoEc/5AIKgt1rxNvXtg5e0vnAH4Z3tADsdr4duFM9Q2Zz56stySK7wjDxA+YbaQo/+7TsWrw3b2JxCgjpAEkZamyRx0bemDN5iEIEqjVVi2m4tNhxhRQCAmptlRJUjG6SU9YSCJfOAPaQV/M7uiUxHnrdVUI8P1JkispiS+YDIjfkmoaPpP0okj3/yjONZm4EciBdxJyUUiqOdQ9qK7IfJnYEe1wAhzqwc/RLpFygSCALgTQNoQkIFTJqg1Z+tw9fPCKhKi6aQHBAEN7aKSBUF8LXBAETgvJAdG2EtWEFDkA2o+mdXPzsVNHXDsCaVya7kt5LJ7bsmsyjKhNIUI3WfingNv4mT1KA658HoYUXHdrC9hUk9RM7XtPCRdf7PV7faKGbiEqseb+K7dVSg+PpzN0xHossHkd2V+
    TELEGRAM_BOT_TOKEN: AgCxq5wFd+Hf4h+77TgselRE1MRtK0TvcWrYGu5TebqWtzgjFG1gZtoTnxeT1XFQOP3ZWJQ/MvT2cZ0ZARnB7Z0tmEc7C/1sA16zb7SKNxwV83yOGH1Onv/a2UGr2NFOSrgpPY1XA7APaDU+fMzO443BjqevvOXfalWn/LhSj0gZa+WkbJzftX2opNl5QPvgyrcmTuYjnnXnpYAg7TdN0zoZOzhKNJqYUtlVz6YFlGT5m6off2anN5I1RDaLF7WZh/cfCNXs827OusnTr8KSMZLSv1wvYCn+IdKCAE4NfkFSMFqH0ZTkM3MQmmUDfqnhNQIDSAqQZTdA7eC6mK1aBf7Bx4di+/peepr7jNQ2UONA5uwMsi127sgaIU46Z09aluYcfpUnAau1H8WC23QYK7DcT+/5ZKyD+O+jkznqScI9Q2Z+wWFgXayMmiZN12tK3kGfto8etAJDMDZbcdGiEn5qKuqZBiV+EHGNwn+uCN+wJrYlIjaUYt34+N3168X6aaDEfF6KPhZhHIHwUuTwBtmTulf7kNWNCxNH5JEBeQVsjE0CLPNSbvnODZFZz8BGSazEkWe0mTB4LlvPF79Nn5SfyEpOEHRRiLYKrHfS02uRCo6xOhIvjMSzyF9vy4J25fV3e4gIzN+twO6JedjNtZenwt+4l+ZwKdFTlr5rF2dCmWQEwk5cwxQqhnF6QHED+Vfu6YZJKsmflpVq06NeiQ2unPyvBXV/jnU5guNK+H52uO1DEZRGV1uYwNhRf2zC
  template:
    metadata:
      creationTimestamp: null
      name: artic-bot-secrets
      namespace: default

