apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redirect-secrets
  namespace: web-site
spec:
  encryptedData:
    API_KEY: AgAU9xnd4F0l1QmsIIRjZlrc+rVYfSVbu7ELftQJ20tPbCOeDQcKwBtszIopYSedd/qqJpSr8EbW8yThKrL+YxbgizqKyGig1C6kBCpn8y7QCM8DBWdih/t/+olyio8joDBXVF98sIv9HRTUBY6i2pZ2NSM9fLXzHklJwBD6Gk5WTjTMcKbU1Lc0hQSRwCWLmZuj7/GL8y39n1AwPuk7Dre3cecKC8Zd6MFsu92QDHUT2Hqchr2sg0J5Y49u73Lbr/bJ8lw6cgKk2VUzQssofhYMza8nfKkl+9zs3ejEtF3j3FIbmyuL80NwR0JUFrTNqMSbg6tm79bhNqHriuoon5x0crA2BSJDU6R4Qjcridkv4nTwFJ4eiJZ0BE6ILoV9SjIAeORquT6fwTWO0YPInI7FLiok7P1iK9P7vTQ7q6IxIyrYerSDqWFTlCj6Wgo1Oz03AQDfHx23JwHMw4mkOygqqKUUZSC9LVMvF200nDA/246iyQqmsTzEHMUKaPCJZRQ9Xi/x/nCcGQRAa+qgyNAH1dLg/RIpI8xMJRt5eYLURlZ2P+Vcp4Jv9pOCpXxkEoq5d22qPz+4jtmGoGeONAcdJ1ZB3sRTM0PIBGyslWdNWqaWrPHgigJ1EEqxJ+Qt5ufTOsth/tF8EtND5EZvYp/q0poOKCiC7rsjnauYDQAMofTQrUJ4XAfwkdzYmgVjHKr2QzsZIVyA1MN/+MFmcQggqLxaf5pEueI7jDa6qOlK4jUjZkL2ZYX8eCkmzv9pdVexIPONfQuXHGOxVG1TbMUmuoHF+7g9C7o=
  template:
    metadata:
      creationTimestamp: null
      name: redirect-secrets
      namespace: web-site

