apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: frontend-secrets
  namespace: web-site
spec:
  encryptedData:
    NUXT_POSTS_API_KEY: AgAdcVMoOhJvf6I7gltWnnhGIMJOog4/gf2T5y+eEy1URCUKmf/XY6PndRCdWbccJ4BTAOJ7VW+lcu/h5pGqSS2BR+ST4K6Zn932v5QqUfYO7UlMXTrRJGGnbdmBWV9JetAZaPgncyH9Us3fHpULvJUnOIdcNNzMIKOdFwxbP7BuGwkLEEFL4ZWtwmq0kRfbyL1ya9haWlZJQVfOhfAB33+ZIqzOYf28L9BXWoDNAP4Q2nIMmonU24S/ommuypHumgKbV3ho1yDxQrpiSRM7hF0zUn0t1yvMAhI2cUfEJBR5XzVBtOZLoHR71mIFvHNnTw9ThEA20GiADRzngYCAvJoRL9kUR7afkFvkDc2bKvzlayzFy7AF8jVE7RlOvGXPynUPWomF/o4vHDfbzEpbFi3EuU/Vih03C7WhzQBfxxfvg+GdukWrmaLSIUJrjjp2zZ+5ZIzzUCeHXcRByQ/fpv++A/5YOlwAuXnY/YjD0FGrOyY7CIivthX4fVSYTXqAm5MomxW/rIAyV8AX1VEoGb9zohhv5n8wzJpR7oyqdmYNrnc94s0/TUFoL1FmwXSGnHSbZhdltVmavcDaaSQ3f1Hg5gwZhPi5bxepF/UyEGqAY5/95acJ7XZM2Wkr4UHaFpbLnnnSRTzqX0HRwmMcQ7ePCdRBlv0lRZ88k0SeLPyYqAjmsuoftw0e8oesjzjauvtnYSMCq83rfTVesFWcPs4tBp66GJLI5tbx2TgLYkWAgotjzjN3jY52vBhcOPeiAfD/hY6nnEfqvjKJRU7s0O3J0HHWaOgPv8c=
    NUXT_POSTS_API_URL: AgAFXIIuLrhGPmrMoKUm5Ghtb3lKcdfekzlo9uS2Hx4QXU+gqJyus2faSjxmE5unJJ4Cd4OItKA3WjWfT7Hu+LknzEnrdkd2lrGApfazj0vgcbXlvMzgNYcEeC/vmoY8+gQDRMNkOKr3bbI2ZPC9xLPjaY6YwtbDpZxXhjmovxyM49E1y+OnLSR3tlAGJZqJciepPG2H1FCAnDIsV25byhpuezSodWZTfGxhDOqbsmhBkwOBYSbKRjytLw7lx9zbRQzjJBTMhWPj3wE+tJ8yWLWt/Mq8WPAn9AIrNw5IPbgCp8gzmNA34k4jq8AYBBqUjCyNRwBEHFkYr55OGEpjFMUlB7dQvm0X1Yy5VmFNLXarPkZDxslNxXysBwYL+D5c4mUSIWGugLYG36/IGGPC/MJrfazNParevslx5SHL8gSTbfAMSLIJNV9+jlYO7ymlDXMTXRMzenotijoTZjp6KEESHVKF3mxVbIducjKhw1CNh9b0Of+tr03gKcT/zs4sKRU/fJKE5GGrR34HBE8WtPQId9/un7APLZDFu/0wGDVKgln6loOkW3tPHxF1y8QbY1Az0Dp6sUnn3aRyN+fyMZh5Wq/FDpN54ZBXPnK3wLBtrJrfzzIE4/C/liJkEMiyT6EwRoq/QSQxAGfZRYGOQKtqltrHeTN8g8KSQz2X8GSqzzBuo9NGmKzOMOnQ8b7puv222bQziEEy8tIcpNxIPzkuQ8xTzrhVXhQ=
  template:
    metadata:
      creationTimestamp: null
      name: frontend-secrets
      namespace: web-site

